//
// Created by 86136 on 2022/5/14.
//

#ifndef DATASTRUCTURE_CLASSDESIGN_SRC_INSERTSORT_H_
#define DATASTRUCTURE_CLASSDESIGN_SRC_INSERTSORT_H_
#include "sqtype.h"
void InsertSort(SqType r[], int n);
#endif //DATASTRUCTURE_CLASSDESIGN_SRC_INSERTSORT_H_
