//
// Created by 86136 on 2022/5/22.
//

#ifndef DATASTRUCTURE_CLASSDESIGN_INCLUDE_MERGINGSORT_H_
#define DATASTRUCTURE_CLASSDESIGN_INCLUDE_MERGINGSORT_H_
#include "sqtype.h"
void MergeSort(SqType r[], int n);
#endif //DATASTRUCTURE_CLASSDESIGN_INCLUDE_MERGINGSORT_H_
