//
// Created by 86136 on 2022/5/14.
//

#ifndef DATASTRUCTURE_CLASSDESIGN_INCLUDE_SQTYPE_H_
#define DATASTRUCTURE_CLASSDESIGN_INCLUDE_SQTYPE_H_

typedef struct {
  int key;
} SqType;

#endif //DATASTRUCTURE_CLASSDESIGN_INCLUDE_SQTYPE_H_
